# Generated by Django 3.2.17 on 2023-04-16 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20230416_1325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuploadfile',
            name='type',
        ),
    ]
