# Generated by Django 3.2.17 on 2023-04-17 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_remove_myuploadfile_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuploadfile',
            name='type',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
